/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package main;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEFINE_KEYWORD = 5;
  /** RegularExpression Id. */
  int CONDITION_KEYWORD = 6;
  /** RegularExpression Id. */
  int ELSE_KEYWORD = 7;
  /** RegularExpression Id. */
  int PRIMITIVE_FUNCTIONS = 8;
  /** RegularExpression Id. */
  int DIGITS = 9;
  /** RegularExpression Id. */
  int VARIABLE = 10;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 11;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 12;
  /** RegularExpression Id. */
  int CONSTANT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"define\"",
    "\"cond\"",
    "\"else\"",
    "<PRIMITIVE_FUNCTIONS>",
    "<DIGITS>",
    "<VARIABLE>",
    "\"(\"",
    "\")\"",
    "<CONSTANT>",
  };

}
