/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package main;

public interface ParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTDEFINE = 2;
  public int JJTVAR = 3;
  public int JJTEXPRESSION = 4;
  public int JJTCOND = 5;
  public int JJTELS = 6;
  public int JJTVARIABLE = 7;


  public String[] jjtNodeName = {
    "root",
    "void",
    "define",
    "var",
    "expression",
    "cond",
    "els",
    "variable",
  };
}
/* JavaCC - OriginalChecksum=0b7221645bfd0ebcaceb4636494ceb14 (do not edit this line) */
